#
# The MIT License (MIT)
#
# Copyright (c) 2018-Now rakeliu@126.com
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
# DEALINGS IN THE SOFTWARE.
#

spring:
  application:
    name: eureka-cluster
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      defaultZone: ${constant.eureka-server}

constant:
  eureka-server: http://eureka-server1:18761/eureka, http://eureka-server2:18762/eureka, http://eureka-server3:18763/eureka

---
server:
  port: 18761
eureka:
  instance:
    hostname: eureka-server1
  client:
    service-url:
      defaultZone: http://eureka-server2:18762/eureka, http://eureka-server3:18763/eureka
spring:
  profiles: eureka18761

---
server:
  port: 18762
eureka:
  instance:
    hostname: eureka-server2
  client:
    service-url:
      defaultZone: http://eureka-server1:18761/eureka, http://eureka-server3:18763/eureka
spring:
  profiles: eureka18762

---
server:
  port: 18763
eureka:
  instance:
    hostname: eureka-server3
  client:
    service-url:
      defaultZone: http://eureka-server1:18762/eureka, http://eureka-server2:18763/eureka
spring:
  profiles: eureka18763